version: '3'
services:
  fava:
    image: kaaass/fava-management
    container_name: 'fava'
    restart: always
    ports:
      - "5000:80"
    environment:
      - BEANCOUNT_FILE=/bean/main.bean
      - USERNAME=admin
      - PASSWORD=123456
    volumes:
      - ./data:/bean
